# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d45a77d4cc11166fce3d5d40b01fbb2351993f642264cc6e14668b3b4a818cb1bafb4bba5a9f5089d00e7501d2db53110f7eee44f25df5d3cb462893ffa119

test:
  secret_key_base: fba9e6017175bc22d39ca8fb5cfc370626497ebc3d86c658f6c85e68206f5079ce0913fba4b68f00ffa9787fec3d01eb75003dc5ccc490046d604d8afa1f1482

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
